#---------------------------------------------------------
# llegir label check: read-only, non-graphical
#---------------------------------------------------------
# Run with `Rscript validate_labels.R` from inside this workspace. Replays
# every labels/<module_id>.json through llegir's synthesis post-processing
# (schema validation, citation/direction faithfulness, significance wording)
# and writes scratch/label_validation.tsv. Do not edit this file.

suppressPackageStartupMessages(library(llegir))
options(llegir.agent_session = TRUE)

report <- llegir::check_agent_labels('.')
utils::write.table(report, file.path('scratch', 'label_validation.tsv'), sep = '\t', row.names = FALSE, quote = FALSE)

cat(sprintf('%d of %d modules ok\n', sum(report$status == 'ok'), sum(report$status != 'unexpected')))
print(table(report$status))

not_ok <- report[report$status != 'ok', ]
if (nrow(not_ok) > 0) {
    cat('\nModules to fix:\n')
    for (i in seq_len(nrow(not_ok))) {
        cat(sprintf('- %s [%s] %s\n', not_ok$module_id[i], not_ok$status[i], not_ok$detail[i]))
    }
}
